def PLAYER_THRUST = 2
def PLAYER_DEACCELERATION = 2
export PLAYER_THRUST
export PLAYER_DEACCELERATION

def DEFAULT_MOVEMENT_VALUE = 20
def DEFAULT_AMMO_VALUE = 50
def DEFAULT_GEM_VALUE = 0

export DEFAULT_GEM_VALUE
export DEFAULT_AMMO_VALUE
export DEFAULT_MOVEMENT_VALUE