
; *** Player movement ****************

def PLAYER_THRUST = 2
def PLAYER_DEACCELERATION = 1
export PLAYER_THRUST
export PLAYER_DEACCELERATION

; *** Enemies *************************

def MAX_ENEMIES = 10
def ENEMIES_SPEED = 2
export MAX_ENEMIES
export ENEMIES_SPEED

def MINE_COUNTDOWN_AMOUNT = 80 ; Frames until mine explodes after triggered
export MINE_COUNTDOWN_AMOUNT

; *** Game settings ********************

def FRAMES_BETWEEN_SCROLL = 8
export FRAMES_BETWEEN_SCROLL

def DEFAULT_MOVEMENT_VALUE = 20
def DEFAULT_AMMO_VALUE = 50
def DEFAULT_GEM_VALUE = 0

export DEFAULT_GEM_VALUE
export DEFAULT_AMMO_VALUE
export DEFAULT_MOVEMENT_VALUE